### ISSUE TITLE
Customizing the alert message that pops up when the user taps log out 

### ISSUE THREAD

**Issue by ahmedbahgatfl** [gary-archer/oauth.mobilesample.ios#13]
I'm trying to change the alert message that pops up to the user when the user taps Logout button, because the current one is misleading as it is the same message for signing the user in , is there a way to change it?

![Simulator Screen Shot - iPhone 14 Pro - 2023-09-21 at 15 47 35](https://github.com/gary-archer/oauth.mobilesample.ios/assets/142428680/9865b5d8-7e35-431c-b473-c30dd927e75f)

**Comment by gary-archer** [comment]
Nope - you can't change it, and it is a usability issue. The best resolution is to implement logout by simply removing tokens, then including the `prompt=none` OIDC parameter on the next login. I would do this in my example, but AWS Cogniti does not support the prompt parameter. See [this example](https://github.com/curityio/openid-client-ios-appauth-dcr/blob/main/Source/AppAuthHandler.swift#L83).
