### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code on my MAC arm64 M1

### ISSUE THREAD

**Issue by yolepro** [gary-archer/oauth.mobilesample.ios#19]
I clone your repo and try to start your project using X-code on my Macbook M1 pro but it is not compiling and showing this message :
Command PhaseScriptExecution failed with a nonzero exit code

Would you have any idea?

**Comment by gary-archer** [comment]
Hmm - don't think I can help you with that one. Feels like something environmental. I see some similar posts on that issue if I google online.

**Comment by yolepro** [comment]
I understand. I will try to fix it myself today and give you feedback if I find something.

**Comment by yolepro** [comment]
Finally I found the source of the problem which where related to the Run script Build phase. The swiftlint seems to be not understood. I just removed it, compile again and no more errors.
